In [1]:
import sys
import math
import pandas as pd
import geopandas as gpd

# import custom modules
sys.path.append('../../utils/')
import data_paths

In [12]:
loc_mst = gpd.read_file(data_paths.MST_COUNTING_PATH + 'mst_locations_selected.gpkg')
loc_bast = gpd.read_file(data_paths.BAST_COUNTING_PATH + 'bast_locations_selected.gpkg')
loc = pd.concat([loc_mst, loc_bast], ignore_index=True)
loc['valid'] = False

In [19]:
# import counting data
cnt = pd.read_parquet(data_paths.COUNTING_PATH + "counting_data_combined_until2024_v2.parquet")
valid_road_links = cnt[cnt['valid']]['road_link_id'].unique()

In [20]:
for idx, row in loc.iterrows():
    if row['road_link_id'] in valid_road_links:
        loc.at[idx, 'valid'] = True

In [22]:
loc[loc['valid']]

,MST_ID,DETEKTOR_ID,FAHRTRICHTUNG,MQ_ID,road_link_id,has_speed,geometry,valid
37,4010,4010021,S,401002.0,80645,1.0,POINT (11.58014 48.10688),True
38,4010,4010022,S,401002.0,80645,1.0,POINT (11.58017 48.1069),True
39,4010,4010012,N,401001.0,80645,1.0,POINT (11.5804 48.10698),True
40,4010,4010013,N,401001.0,80645,1.0,POINT (11.58036 48.10696),True
41,4010,4010014,N,401001.0,80645,1.0,POINT (11.58032 48.10695),True
...,...,...,...,...,...,...,...,...
386,9221,92212,S,NaN,594870750,NaN,POINT (11.59046 48.09067),True
389,9820,98201,N,NaN,595969067,NaN,POINT (11.58807 48.22245),True
390,9820,98202,S,NaN,595969067,NaN,POINT (11.58707 48.22245),True
391,9810,98101,O,NaN,626649398,NaN,POINT (11.45619 48.22996),True
392,9810,98102,W,NaN,624703532,NaN,POINT (11.45644 48.23021),True

In [23]:
loc.to_file(data_paths.COUNTING_PATH + 'counting_locations_with_validity.gpkg', driver='GPKG', index=False)